import { INTERNAL_PATHS } from "./internal.path.routes";

export const INTERNAL_ROUTES_PATHS = {

    /**
     * Errores
     */
    ERROR_DEFAUL: `/${INTERNAL_PATHS.ERROR}`,
    ERROR_FOUND: `/${INTERNAL_PATHS.ERROR}/${INTERNAL_PATHS.NOT_FOUND}`,
    ERROR_SERVER: `/${INTERNAL_PATHS.ERROR}/${INTERNAL_PATHS.SERVER_FOUND}`,
    ERROR_WORKING: `/${INTERNAL_PATHS.ERROR}/${INTERNAL_PATHS.WORKING}`,

    /**
     * Autentificacion
     */
    AUTH_DEFAULT: `/${INTERNAL_PATHS.AUTH_DEFAULT}`,
    AUTH_LOGIN: `/${INTERNAL_PATHS.AUTH_DEFAULT}/${INTERNAL_PATHS.AUTH_LOGIN}`,

    /**
     * Home
     */
    DASHBOARD: `/${INTERNAL_PATHS.DASHBOARD}`,
    HOME: `/${INTERNAL_PATHS.DASHBOARD}/${INTERNAL_PATHS.HOME}`,

    /**
     * Bitacora
     */
    BITACORA_DEFAULT: `/${INTERNAL_PATHS.DASHBOARD}/${INTERNAL_PATHS.BITACORA_DEFAULT}`,
    BITACORA_REGISTRO: `/${INTERNAL_PATHS.DASHBOARD}/${INTERNAL_PATHS.BITACORA_DEFAULT}/${INTERNAL_PATHS.BITACORA_NUEVO}`,
    BITACORA_MODIFICAR: `/${INTERNAL_PATHS.DASHBOARD}/${INTERNAL_PATHS.BITACORA_DEFAULT}/${INTERNAL_PATHS.BITACORA_MODIFICAR}`,
    BITACORA_LISTAR: `/${INTERNAL_PATHS.DASHBOARD}/${INTERNAL_PATHS.BITACORA_DEFAULT}/${INTERNAL_PATHS.BITACORA_LISTADO}`,
    BITACORA_DETALLE: `/${INTERNAL_PATHS.DASHBOARD}/${INTERNAL_PATHS.BITACORA_DEFAULT}/${INTERNAL_PATHS.BITACORA_DETALLE}`,

    /**
     * Residentes
     */
    RESIDENTES_DEFAULT: `/${INTERNAL_PATHS.DASHBOARD}/${INTERNAL_PATHS.RESIDENTES_DEFAULT}`,
    RESIDENTES_LISTAR: `/${INTERNAL_PATHS.DASHBOARD}/${INTERNAL_PATHS.RESIDENTES_DEFAULT}/${INTERNAL_PATHS.RESIDENTES_LISTADO}`,

    /**
     * Vehiculo
     */
    VEHICULO_DEFAULT: `/${INTERNAL_PATHS.DASHBOARD}/${INTERNAL_PATHS.VEHICULO_DEFAULT}`,
    VEHICULO_LISTADO: `/${INTERNAL_PATHS.DASHBOARD}/${INTERNAL_PATHS.VEHICULO_DEFAULT}/${INTERNAL_PATHS.VEHICULO_LISTADO}`,
    VEHICULO_TIPOS: `/${INTERNAL_PATHS.DASHBOARD}/${INTERNAL_PATHS.VEHICULO_DEFAULT}/${INTERNAL_PATHS.VEHICULO_TIPOS}`,

    /**
     * Usuarios
     */
    USUARIOS_DEFAULT: `/${INTERNAL_PATHS.DASHBOARD}/${INTERNAL_PATHS.USUARIOS_DEFAULT}`,
    USUARIOS_PERFIL: `/${INTERNAL_PATHS.DASHBOARD}/${INTERNAL_PATHS.USUARIOS_DEFAULT}/${INTERNAL_PATHS.USUARIOS_PERFIL}`,
    USUARIOS_CONFIGURACIONES: `/${INTERNAL_PATHS.DASHBOARD}/${INTERNAL_PATHS.USUARIOS_DEFAULT}/${INTERNAL_PATHS.USUARIOS_CONFIGURACIONES}`,
}
