import { ROUTES_PATHS } from "./path.routes";

export const INTERNAL_PATHS = {

    /**
     * Rutas no encontradas
     */
    ERROR: `${ROUTES_PATHS.ERROR.ERROR_DEFAULT}`,
    WORKING: `${ROUTES_PATHS.ERROR.WORKING}`,
    NOT_FOUND: `${ROUTES_PATHS.ERROR.E404}`,
    SERVER_FOUND: `${ROUTES_PATHS.ERROR.E500}`,

    /**
     * Autentificacion
     */
    AUTH_DEFAULT: `${ROUTES_PATHS.AUTH.DEFAULT}`,
    AUTH_LOGIN: `${ROUTES_PATHS.AUTH.LOGIN}`,

    /**
     * Usuarios
     */
    USUARIOS_DEFAULT: `${ROUTES_PATHS.AUTH.USUARIOS}`,
    USUARIOS_PERFIL: `${ROUTES_PATHS.ACCIONES.DETALLE}`,
    USUARIOS_CONFIGURACIONES: `${ROUTES_PATHS.ACCIONES.MODIFICAR}`,

    /**
     * Dashboard
     */
    DASHBOARD: `${ROUTES_PATHS.PANEL.DASHBOARD}`,
    HOME: `${ROUTES_PATHS.PRINCIPALES.HOME}`,

    /**
     * Bitacora
     */
    BITACORA_DEFAULT: `${ROUTES_PATHS.PRINCIPALES.BITACORA}`,
    BITACORA_NUEVO: `${ROUTES_PATHS.ACCIONES.NUEVO}`,
    BITACORA_LISTADO: `${ROUTES_PATHS.ACCIONES.LISTAR}`,
    BITACORA_DETALLE: `${ROUTES_PATHS.ACCIONES.DETALLE}`,
    BITACORA_MODIFICAR: `${ROUTES_PATHS.ACCIONES.MODIFICAR}`,

    /**
     * Residentes
     */
    RESIDENTES_DEFAULT: `${ROUTES_PATHS.PRINCIPALES.RESIDENTES}`,
    RESIDENTES_LISTADO: `${ROUTES_PATHS.ACCIONES.LISTAR}`,

    /**
     * Vehiculo
     */
    VEHICULO_DEFAULT: `${ROUTES_PATHS.PRINCIPALES.VEHICULO}`,
    VEHICULO_LISTADO: `${ROUTES_PATHS.ACCIONES.LISTAR}`,
    VEHICULO_TIPOS: `${ROUTES_PATHS.ESPECIALES.TIPOS}`
}
